name: SQL ðŸŽ³

on:
  push:
#    paths:
#      - '**.sql'
  pull_request:
#    paths:
#      - '**.sql'

jobs:
  test-migration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docker
    runs-on: ubuntu-latest
    strategy:
      qgis_version: [
          "3.40",
          "3.44",
        ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Running tests
        run: make docker-test QGIS_VERSION=${{ matrix.qgis_version }}
